import { Inter, Outfit } from "next/font/google";
import "./globals.css";
// import "react-toastify/dist/ReactToastify.css"
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import Banner from "@/components/home/Banner";
import UserSync from "@/components/profile/UserSync";
// import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ClerkSync from "@/components/ClerkSync";
const inter = Inter({subsets:['latin']})
export const metadata = {
  title: "EduTom",
  description: "Generated by Pranav &Ritik ",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
      <body className="flex flex-col min-h-screen w-screen">
   
        <ReactQueryProvider>
          <ClerkSync />
      <Header />
        <main className="flex-grow mt-20  bg-white text-black">
          <UserSync />
          {/* <Toaster /> */}
          {children}
        </main>
       <Banner />
       <Footer />
       </ReactQueryProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}
