import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import Banner from "@/components/home/Banner";
const inter = Inter({subsets:['latin']})
export const metadata = {
  title: "EduTom",
  description: "Generated by Pranav &Ritik ",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
      <body className="flex flex-col min-h-screen w-screen">
      {/* put header */}
      <Header />
        <main className="flex-grow mt-20">
          {children}
        </main>
       {/* put footer */}
       <Banner />
       <Footer />
      </body>
    </html>
     </ClerkProvider>
  );
}
// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className="flex flex-col min-h-screen w-full">
//           <Header /> {/* stays on top across all routes */}
          
//           <main className="flex-grow">
//             {children} {/* profile layout will come here */}
//           </main>

//           <Banner />
//           <Footer />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
